[package]
edition = '2018'
name = "mdlint-cli"
version = "0.1.1"
authors = ["gnostr admin@gnostr.org", "Roberto Huertas <roberto.huertas@outlook.com>"]

[dependencies]
mdlint = { path = "../mdlint" }
