[package]
edition = '2018'
name = "mdlint"
version = "0.1.1"
authors = ["gnostr admin@gnostr.org", "Roberto Huertas <roberto.huertas@outlook.com>"]

[dependencies]
console = "0.6.2"
comrak = "0.2.14"
typed-arena = "1.4.1"
regex = "1"
